# -*- coding: utf-8 -*-
"""automobile_analise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SywF0jInSONkZPgNab-ISRVVBe9XZ9dX

prompt 1
"""

# ==========================================================
# CÉLULA 1 - Importação e carregamento da base
# ==========================================================

import pandas as pd
import numpy as np
from google.colab import files

uploaded = files.upload()

arquivo = next(iter(uploaded))
df_original = pd.read_csv(arquivo)

df = df_original.copy()

print("Primeiras linhas:")
display(df.head())

print(f"Dimensões: {df.shape}")

print("\nTipos identificados pelo pandas:")
display(df.dtypes.rename("dtype"))

# ==========================================================
# CÉLULA 2 - Classificação estatística das variáveis
# ==========================================================

qualitativa_ordinal = [
    "symboling"
]

qualitativa_nominal = [
    "make",
    "fuel_type",
    "aspiration",
    "body_style",
    "drive_wheels",
    "engine_location",
    "engine_type",
    "fuel_system"
]

quantitativa_discreta = [
    "num_of_doors",
    "num_of_cylinders"
]

classificacao = {}

for v in qualitativa_ordinal:
    classificacao[v] = "Qualitativa ordinal"

for v in qualitativa_nominal:
    classificacao[v] = "Qualitativa nominal"

for v in quantitativa_discreta:
    classificacao[v] = "Quantitativa discreta"

for v in df.columns:
    if v not in classificacao:
        classificacao[v] = "Quantitativa contínua"

tabela_variaveis = pd.DataFrame({
    "Variável": df.columns,
    "Tipo inicial (pandas)": [str(df[c].dtype) for c in df.columns],
    "Classificação estatística": [classificacao[c] for c in df.columns],
    "Valores distintos": [df[c].nunique(dropna=True) for c in df.columns],
    "Exemplos": [
        ", ".join(df[c].dropna().astype(str).unique()[:5])
        for c in df.columns
    ]
})

display(tabela_variaveis)

# ==========================================================
# CÉLULA 3 - Tratamento dos dados inválidos
# ==========================================================

# Remove espaços das colunas textuais
colunas_texto = df.select_dtypes(include="object").columns

for c in colunas_texto:
    df[c] = df[c].str.strip()

# Padroniza valores inválidos
df.replace(
    ["?", "", "NA", "N/A", "null", "None"],
    np.nan,
    inplace=True
)

df.replace([np.inf, -np.inf], np.nan, inplace=True)

# Conversão explícita das variáveis discretas
mapa_portas = {
    "two": 2,
    "four": 4
}

mapa_cilindros = {
    "two": 2,
    "three": 3,
    "four": 4,
    "five": 5,
    "six": 6,
    "eight": 8,
    "twelve": 12
}

df["num_of_doors"] = df["num_of_doors"].map(mapa_portas)
df["num_of_cylinders"] = df["num_of_cylinders"].map(mapa_cilindros)

# Conversão das variáveis quantitativas
variaveis_quantitativas = [
    c for c, t in classificacao.items()
    if t in ["Quantitativa discreta", "Quantitativa contínua"]
]

for c in variaveis_quantitativas:
    df[c] = pd.to_numeric(df[c], errors="coerce")

# Resumo dos valores inválidos
invalidos = df.isna().sum()

tabela_invalidos = pd.DataFrame({
    "Valores inválidos": invalidos,
    "% inválidos": (invalidos / len(df) * 100).round(2)
})

display(tabela_invalidos)

linhas_invalidas = df.isna().any(axis=1).sum()

print(f"Total de linhas com pelo menos um valor inválido: {linhas_invalidas}")

# ==========================================================
# CÉLULA 4 - Limpeza e tipos finais
# ==========================================================

linhas_antes = len(df)

df_clean = df.dropna().copy()

linhas_depois = len(df_clean)
linhas_removidas = linhas_antes - linhas_depois

# Symboling como categoria ordenada
categorias_symboling = [-2, -1, 0, 1, 2, 3]

df_clean["symboling"] = pd.Categorical(
    df_clean["symboling"].astype(int),
    categories=categorias_symboling,
    ordered=True
)

# Variáveis qualitativas nominais
for c in qualitativa_nominal:
    df_clean[c] = df_clean[c].astype("category")

print(f"Linhas antes da limpeza : {linhas_antes}")
print(f"Linhas após a limpeza   : {linhas_depois}")
print(f"Linhas removidas        : {linhas_removidas}")
print(f"Percentual removido     : {100 * linhas_removidas / linhas_antes:.2f}%")

print("\nPrimeiras linhas do conjunto limpo:")
display(df_clean.head())

print("\nTipos finais:")
display(df_clean.dtypes.rename("dtype"))

print("\nPossui valores ausentes?")
print(df_clean.isna().sum().sum() == 0)

"""prompt 2"""

# ==========================================================
# CÉLULA 1 - Configurações gerais
# ==========================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

cm = 1 / 2.54

plt.rcParams["font.family"] = "serif"
plt.rcParams["text.color"] = "black"
plt.rcParams["axes.labelcolor"] = "black"
plt.rcParams["axes.edgecolor"] = "black"
plt.rcParams["axes.titlecolor"] = "black"
plt.rcParams["xtick.color"] = "black"
plt.rcParams["ytick.color"] = "black"
plt.rcParams["legend.labelcolor"] = "black"

cmap = plt.cm.viridis

# ==========================================================
# CÉLULA 2 - Gráfico 1
# Quantidade de veículos por fabricante
# ==========================================================

contagem = df_clean["make"].value_counts()

cores = cmap(np.linspace(0.15, 0.90, len(contagem)))

plt.figure(figsize=(18*cm, 10*cm))

barras = plt.bar(
    contagem.index,
    contagem.values,
    color=cores
)

for barra in barras:
    plt.text(
        barra.get_x() + barra.get_width()/2,
        barra.get_height(),
        f"{int(barra.get_height())}",
        ha="center",
        va="bottom",
        fontsize=9
    )

plt.title("Quantidade de veículos por fabricante")
plt.xlabel("Fabricante")
plt.ylabel("Quantidade")

plt.xticks(rotation=45, ha="right")

plt.tight_layout()
plt.show()

# ==========================================================
# CÉLULA 3 - Gráfico 2
# Consumo médio por fabricante
# ==========================================================

consumo = (
    df_clean
    .groupby("make")[["city_mpg", "highway_mpg"]]
    .mean()
    .sort_values("city_mpg")
)

x = np.arange(len(consumo))
largura = 0.38

cores = cmap([0.25, 0.75])

plt.figure(figsize=(20*cm, 10*cm))

plt.bar(
    x - largura/2,
    consumo["city_mpg"],
    largura,
    color=cores[0],
    label="City MPG"
)

plt.bar(
    x + largura/2,
    consumo["highway_mpg"],
    largura,
    color=cores[1],
    label="Highway MPG"
)

plt.xticks(x, consumo.index, rotation=45, ha="right")

plt.title("Consumo médio por fabricante")
plt.xlabel("Fabricante")
plt.ylabel("MPG médio")

plt.legend()

plt.tight_layout()
plt.show()

# ==========================================================
# CÉLULA 4 - Gráfico 3
# Potência e preço por número de portas
# ==========================================================

categorias = sorted(df_clean["num_of_doors"].unique())

cores = cmap(np.linspace(0.2, 0.8, len(categorias)))

plt.figure(figsize=(16*cm, 10*cm))

for cor, portas in zip(cores, categorias):

    dados = df_clean[df_clean["num_of_doors"] == portas]

    plt.scatter(
        dados["horsepower"],
        dados["price"],
        s=45,
        alpha=0.7,
        color=cor,
        label=f"{int(portas)} portas"
    )

plt.title("Potência e preço por número de portas")
plt.xlabel("Horsepower")
plt.ylabel("Preço")

plt.legend(title="Número de portas")

plt.tight_layout()
plt.show()

"""prompt 3"""

# ==========================================================
# CÉLULA 1 - Importações e seleção das variáveis categóricas
# ==========================================================

import pandas as pd
from scipy.stats import chi2_contingency
from itertools import combinations

variaveis_categoricas = tabela_variaveis.loc[
    tabela_variaveis["Classificação estatística"].isin(
        ["Qualitativa nominal", "Qualitativa ordinal"]
    ),
    "Variável"
].tolist()

print("Variáveis categóricas selecionadas:")
print(variaveis_categoricas)

# ==========================================================
# CÉLULA 2 - Testes de associação
# ==========================================================

alpha = 0.05

resultados = []

for var1, var2 in combinations(variaveis_categoricas, 2):

    tabela = pd.crosstab(df_clean[var1], df_clean[var2])

    qui2, p_valor, gl, _ = chi2_contingency(tabela)

    significativo = "Sim" if p_valor < alpha else "Não"

    conclusao = (
        "Existe associação estatisticamente significativa ao nível de 5%."
        if p_valor < alpha
        else "Não foram encontradas evidências estatísticas suficientes de associação ao nível de 5%."
    )

    resultados.append({
        "variavel_1": var1,
        "variavel_2": var2,
        "qui_quadrado": round(qui2, 4),
        "graus_liberdade": gl,
        "p_valor": round(p_valor, 6),
        "significativo_5_porcento": significativo,
        "conclusao": conclusao
    })

resultados_associacao = (
    pd.DataFrame(resultados)
    .sort_values("p_valor")
    .reset_index(drop=True)
)

display(resultados_associacao)

# ==========================================================
# CÉLULA 3 - Resultados separados
# ==========================================================

print("Pares com associação estatisticamente significativa (5%)")
display(
    resultados_associacao[
        resultados_associacao["significativo_5_porcento"] == "Sim"
    ]
)

print("Pares sem associação estatisticamente significativa (5%)")
display(
    resultados_associacao[
        resultados_associacao["significativo_5_porcento"] == "Não"
    ]
)

"""prompt 4"""

# ==========================================================
# CÉLULA 1 - Importações e seleção das variáveis quantitativas
# ==========================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import pearsonr
from itertools import combinations

variaveis_quantitativas = tabela_variaveis.loc[
    tabela_variaveis["Classificação estatística"].isin(
        ["Quantitativa discreta", "Quantitativa contínua"]
    ),
    "Variável"
].tolist()

print("Variáveis quantitativas selecionadas:")
print(variaveis_quantitativas)

# ==========================================================
# CÉLULA 2 - Matriz de correlação
# ==========================================================

matriz_correlacao = df_clean[variaveis_quantitativas].corr(method="pearson")

display(matriz_correlacao)

# ==========================================================
# CÉLULA 3 - Correlação entre todos os pares
# ==========================================================

alpha = 0.05

resultados = []

for var1, var2 in combinations(variaveis_quantitativas, 2):

    r, p = pearsonr(df_clean[var1], df_clean[var2])

    if np.isclose(r, -1):
        classificacao = "Perfeitamente negativa"

    elif -1 < r < -0.30:
        classificacao = "Média negativa"

    elif -0.30 <= r <= 0.30:
        classificacao = "Nula ou muito fraca"

    elif 0.30 < r < 1:
        classificacao = "Média positiva"

    elif np.isclose(r, 1):
        classificacao = "Perfeitamente positiva"

    else:
        classificacao = "Nula ou muito fraca"

    resultados.append({
        "variavel_1": var1,
        "variavel_2": var2,
        "coeficiente_pearson": round(r, 4),
        "p_valor": round(p, 6),
        "classificacao": classificacao,
        "significativo_5_porcento": "Sim" if p < alpha else "Não"
    })

resultados_correlacao = (
    pd.DataFrame(resultados)
    .sort_values(
        by="coeficiente_pearson",
        key=lambda x: np.abs(x),
        ascending=False
    )
    .reset_index(drop=True)
)

display(resultados_correlacao)

# ==========================================================
# CÉLULA 4 - Resultados por classificação
# ==========================================================

categorias = [
    "Perfeitamente negativa",
    "Média negativa",
    "Nula ou muito fraca",
    "Média positiva",
    "Perfeitamente positiva"
]

for categoria in categorias:

    print(f"\n{categoria}")

    display(
        resultados_correlacao[
            resultados_correlacao["classificacao"] == categoria
        ]
    )

# ==========================================================
# CÉLULA 5 - Mapa de calor da correlação
# ==========================================================

cm = 1 / 2.54

plt.rcParams["font.family"] = "serif"
plt.rcParams["text.color"] = "black"
plt.rcParams["axes.labelcolor"] = "black"
plt.rcParams["axes.titlecolor"] = "black"
plt.rcParams["xtick.color"] = "black"
plt.rcParams["ytick.color"] = "black"

fig, ax = plt.subplots(figsize=(18*cm, 16*cm))

imagem = ax.imshow(
    matriz_correlacao,
    cmap="viridis",
    vmin=-1,
    vmax=1
)

ax.set_xticks(np.arange(len(variaveis_quantitativas)))
ax.set_yticks(np.arange(len(variaveis_quantitativas)))

ax.set_xticklabels(variaveis_quantitativas, rotation=90)
ax.set_yticklabels(variaveis_quantitativas)

for i in range(len(variaveis_quantitativas)):
    for j in range(len(variaveis_quantitativas)):
        ax.text(
            j,
            i,
            f"{matriz_correlacao.iloc[i, j]:.2f}",
            ha="center",
            va="center",
            color="black",
            fontsize=8
        )

plt.title("Mapa de calor da matriz de correlação")

plt.colorbar(imagem)

plt.tight_layout()
plt.show()